"""job_apply table creation v1.0

Revision ID: 6e67599fc8dc
Revises: fd83162a6f51
Create Date: 2025-04-21 12:59:07.557747

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6e67599fc8dc"
down_revision: Union[str, None] = "fd83162a6f51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "job_apply_mst",
        sa.Column("applied_date", sa.DateTime(), nullable=True),
        sa.Column("status_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["jobs_mst.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["status_id"], ["job_status.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users_mst.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_apply_mst_id"), "job_apply_mst", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_apply_mst_id"), table_name="job_apply_mst")
    op.drop_table("job_apply_mst")
    op.drop_table("job_status")
    # ### end Alembic commands ###
