"""User_mst table added

Revision ID: bf1849d9dc91
Revises: 27cdddba5f42
Create Date: 2025-04-20 15:40:04.191991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf1849d9dc91'
down_revision: Union[str, None] = '27cdddba5f42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_mst_id', table_name='jobs_mst')
    op.drop_index('ix_jobs_mst_title', table_name='jobs_mst')
    op.drop_table('jobs_mst')
    op.drop_index('ix_company_mst_id', table_name='company_mst')
    op.drop_index('ix_company_mst_name', table_name='company_mst')
    op.drop_table('company_mst')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_mst',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('founder', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('founded_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('company_mst_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('isActive', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='company_mst_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_company_mst_name', 'company_mst', ['name'], unique=False)
    op.create_index('ix_company_mst_id', 'company_mst', ['id'], unique=False)
    op.create_table('jobs_mst',
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('posted_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('isActive', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('company', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company'], ['company_mst.id'], name='jobs_mst_company_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='jobs_mst_pkey')
    )
    op.create_index('ix_jobs_mst_title', 'jobs_mst', ['title'], unique=False)
    op.create_index('ix_jobs_mst_id', 'jobs_mst', ['id'], unique=False)
    # ### end Alembic commands ###
