"""user_mst_table added v.3

Revision ID: fd83162a6f51
Revises: bf1849d9dc91
Create Date: 2025-04-20 16:09:53.507778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd83162a6f51'
down_revision: Union[str, None] = 'bf1849d9dc91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_mst',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('founder', sa.String(), nullable=True),
    sa.Column('founded_date', sa.Date(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_mst_id'), 'company_mst', ['id'], unique=False)
    op.create_index(op.f('ix_company_mst_name'), 'company_mst', ['name'], unique=False)
    op.create_table('users_mst',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_mst_id'), 'users_mst', ['id'], unique=False)
    op.create_table('jobs_mst',
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('company', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company'], ['company_mst.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_mst_id'), 'jobs_mst', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_mst_title'), 'jobs_mst', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_mst_title'), table_name='jobs_mst')
    op.drop_index(op.f('ix_jobs_mst_id'), table_name='jobs_mst')
    op.drop_table('jobs_mst')
    op.drop_index(op.f('ix_users_mst_id'), table_name='users_mst')
    op.drop_table('users_mst')
    op.drop_index(op.f('ix_company_mst_name'), table_name='company_mst')
    op.drop_index(op.f('ix_company_mst_id'), table_name='company_mst')
    op.drop_table('company_mst')
    # ### end Alembic commands ###
